# Generated by Django 4.2 on 2023-04-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('total_spend', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_duration', models.IntegerField()),
                ('task_added', models.DateTimeField(auto_now=True)),
                ('task_description', models.CharField(max_length=1000)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timelogs_backend.categories')),
            ],
        ),
    ]
