# Generated by Django 4.2 on 2023-04-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='TimeLogs',
            new_name='TimeLog',
        ),
    ]
