# Generated by Django 4.2 on 2023-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs_backend', '0002_rename_categories_category_rename_timelogs_timelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='total_spend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='task_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
