# Generated by Django 4.2 on 2023-04-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs_backend', '0003_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='task_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
