# Generated by Django 4.2 on 2023-04-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs_backend', '0004_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelog',
            old_name='task_added',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='timelog',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='timelog',
            old_name='task_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='timelog',
            old_name='task_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='timelog',
            old_name='task_type',
            new_name='type',
        ),
    ]
